import Frames.Billing.navigationFrame as navigationFrameBilling
import Frames.Inventory.navigationFrame as navigationFrameInventory
import Frames.Customer_Details.navigationFrame as navigationFrameCustomerDetails
import Frames.Bill_History.navigationFrame as navigationFrameBillHistory
import Frames.App_Settings.navigationFrame as navigationFrameAppSettings
import Frames.Overview.navigationFrame as navigationFrameOverview